# Generated by Django 5.1.5 on 2025-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_jobapplication_alter_userprofile_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('experience', models.CharField(default='Not specified', max_length=100)),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
