# Generated by Django 5.1.5 on 2025-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_availability_appointment_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
