# Generated by Django 5.1.5 on 2025-01-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_alter_availability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='reason',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.availability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
    ]
