# Generated by Django 5.1.5 on 2025-01-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_remove_availability_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
