# Generated by Django 5.1.5 on 2025-01-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_remove_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='time',
            field=models.TimeField(default=("14:30:00")),
            preserve_default=False,
        ),
    ]
