# Generated by Django 5.1.5 on 2025-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_alter_availability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
