# Generated by Django 5.1.5 on 2025-01-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_alter_availability_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.TimeField(),
        ),
    ]
