# Generated by Django 5.1.5 on 2025-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_alter_availability_date_alter_availability_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, choices=[('09:00 AM', '09:00 AM'), ('02:00 PM', '02:00 PM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
